name: Build APK and Decompile

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Select build type'
        required: true
        type: choice
        options:
          - original
          - android (non root)
          - switch port

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip openjdk-17-jdk

    - name: Install apktool
      run: |
        wget https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.9.3.jar -O apktool.jar
        sudo mv apktool.jar /usr/local/bin/apktool.jar
        echo -e '#!/bin/bash\njava -jar /usr/local/bin/apktool.jar "$@"' | sudo tee /usr/local/bin/apktool > /dev/null
        sudo chmod +x /usr/local/bin/apktool

    - name: Install uber-apk-signer
      run: |
        wget https://github.com/patrickfav/uber-apk-signer/releases/download/v1.2.1/uber-apk-signer-1.2.1.jar -O uber-apk-signer.jar

      # Install Jadx
    - name: Install Jadx
      run: |
          JADX_VERSION=$(curl -s "https://api.github.com/repos/skylot/jadx/releases/latest" | grep -Po '"tag_name": "v\K[0-9.]+')
          curl -Lo jadx.zip "https://github.com/skylot/jadx/releases/latest/download/jadx-${JADX_VERSION}.zip"
          unzip jadx.zip -d jadx-temp
          mkdir -p /opt/jadx/bin
          mv jadx-temp/bin/jadx /opt/jadx/bin
          mv jadx-temp/bin/jadx-gui /opt/jadx/bin
          mv jadx-temp/lib /opt/jadx
          chmod +x /opt/jadx

      # Install Uber APK signer
    - name: Install Uber APK signer
      run: |
          wget https://github.com/patrickfav/uber-apk-signer/releases/download/v1.2.0/uber-apk-signer-1.2.0.jar

      # Run the build.sh script with the selected build type
    - name: Run build script with selected build type
      run: |
          BUILD_TYPE="${{ github.event.inputs.build_type }}"
          echo "Running build with type: $BUILD_TYPE"
          bash ./build.sh "$BUILD_TYPE"

      # Upload APKs to GitHub release
    - name: Upload APK to Release
      uses: softprops/action-gh-release@v1
      with:
          files: |
            original/apk/*.apk
            android/apk/*.apk
            switch/apk/*.apk
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
