name: Build APK and Decompile

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Select build type'
        required: true
        type: choice
        options:
          - original
          - android (non root)
          - switch port

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip openjdk-17-jdk apktool

    - name: Install Android SDK Command Line Tools and Build Tools
      run: |
        mkdir -p "$HOME/Android/Sdk/cmdline-tools"
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d "$HOME/Android/Sdk/cmdline-tools"
        mv "$HOME/Android/Sdk/cmdline-tools/cmdline-tools" "$HOME/Android/Sdk/cmdline-tools/latest"
        echo "ANDROID_SDK_ROOT=$HOME/Android/Sdk" >> $GITHUB_ENV
        echo "$HOME/Android/Sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
        yes | "$HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager" --licenses
        "$HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager" "build-tools;33.0.0" "platform-tools" "platforms;android-33"   
 
      # Install Jadx
    - name: Install Jadx
      run: |
        JADX_VERSION=$(curl -s "https://api.github.com/repos/skylot/jadx/releases/latest" | grep -Po '"tag_name": "v\K[0-9.]+')
        curl -Lo jadx.zip "https://github.com/skylot/jadx/releases/latest/download/jadx-${JADX_VERSION}.zip"
        unzip jadx.zip -d jadx-temp
        sudo mkdir -p /opt/jadx/bin
        sudo mv jadx-temp/bin/* /opt/jadx/bin/
        sudo mv jadx-temp/lib /opt/jadx/
        sudo find /opt/jadx/bin -type f -exec chmod +x {} \;
     
    - name: Clean apktool framework directory
      run: |
        sudo rm -rf "$HOME/.local/share/apktool/framework"
        sudo mkdir -p "$HOME/.local/share/apktool/framework"
        sudo chmod -R 777 "$HOME/.local/share/apktool/framework"   
    
    - name: Add Jadx to PATH
      run: echo "/opt/jadx/bin" >> $GITHUB_PATH
      
      # Install Uber APK signer
    - name: Ensure uber-apk-signer.jar permissions
      run: |
        curl -L https://github.com/patrickfav/uber-apk-signer/releases/download/v1.2.0/uber-apk-signer-1.2.0.jar -o ./uber-apk-signer.jar
        sudo chmod +x ./uber-apk-signer.jar
        
    - name: Clean up .DS_Store files
      run: |
        find . -name '.DS_Store' -type f -delete 
        
      # Run the build.sh script with the selected build type
    - name: Run build script with selected build type
      run: |
        BUILD_TYPE="${{ github.event.inputs.build_type }}"
        echo "Running build with type: $BUILD_TYPE"
        bash ./build.sh "$BUILD_TYPE"

      # Upload APKs to GitHub release
    - name: Upload APK to Release
      uses: softprops/action-gh-release@v1
      with:
       files: |
          original/apk/*.apk
          android/apk/*.apk
          switch/apk/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
