name: Build APK and Decompile

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Select build type'
        required: true
        type: choice
        options:
          - original
          - android (non root)
          - switch port

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip openjdk-17-jdk apktool
      
      # Install Jadx
    - name: Install Jadx
      run: |
        JADX_VERSION=$(curl -s "https://api.github.com/repos/skylot/jadx/releases/latest" | grep -Po '"tag_name": "v\K[0-9.]+')
        curl -Lo jadx.zip "https://github.com/skylot/jadx/releases/latest/download/jadx-${JADX_VERSION}.zip"
        unzip jadx.zip -d jadx-temp
        sudo mkdir -p /opt/jadx/bin
        sudo mv jadx-temp/bin/* /opt/jadx/bin/
        sudo mv jadx-temp/lib /opt/jadx/
        sudo find /opt/jadx/bin -type f -exec chmod +x {} \;
    
    - name: Add Jadx to PATH
      run: echo "/opt/jadx/bin" >> $GITHUB_PATH
      
      # Install Uber APK signer
    - name: Ensure uber-apk-signer.jar permissions
      run: |
        curl -L https://github.com/patrickfav/uber-apk-signer/releases/download/v1.2.0/uber-apk-signer-1.2.0.jar -o ./uber-apk-signer.jar
        sudo chmod +x ./uber-apk-signer.jar
        
      # aapt binary  
    - name: Download aapt binary
      run: |
        mkdir -p tools
        curl -L -o tools/build-tools.zip https://dl.google.com/android/repository/build-tools_r30.0.3-linux.zip
        unzip -q tools/build-tools.zip -d tools
        echo "$GITHUB_WORKSPACE/tools/android-11/build-tools/30.0.3" >> $GITHUB_PATH
        
      # Run the build.sh script with the selected build type
    - name: Run build script with selected build type
      run: |
        BUILD_TYPE="${{ github.event.inputs.build_type }}"
        echo "Running build with type: $BUILD_TYPE"
        bash ./build.sh "$BUILD_TYPE"

      # Upload APKs to GitHub release
    - name: Upload APK to Release
      uses: softprops/action-gh-release@v1
      with:
       files: |
          original/apk/*.apk
          android/apk/*.apk
          switch/apk/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
