name: Build APK and Decompile

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Select build type'
        required: true
        type: choice
        options:
          - original
          - android (non root)
          - switch port

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip openjdk-17-jdk apktool
      # Install apktool
    - name: Install apktool
      run: |
        sudo wget https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.9.3.jar -O /home/runner/work/Rabbit-R1/apktool.jar
        sudo chmod +r /home/runner/work/Rabbit-R1/apktool.jar
        sudo wget https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool -O /home/runner/work/Rabbit-R1/apktool
        sudo chmod +x /home/runner/work/Rabbit-R1/apktool
      # Install Uber APK signer
    - name: Install uber-apk-signer
      run: |
        wget https://github.com/patrickfav/uber-apk-signer/releases/download/v1.2.1/uber-apk-signer-1.2.1.jar -O /home/runner/work/Rabbit-R1/uber-apk-signer.jar
        sudo chmod +x /home/runner/work/Rabbit-R1/uber-apk-signer.jar
        wget https://github.com/patrickfav/uber-apk-signer/releases/download/v1.2.1/uber-apk-signer-1.2.1.jar -O /home/runner/work/Rabbit-R1/uber-apk-signer
        sudo chmod +x /home/runner/work/Rabbit-R1/uber-apk-signer
        
      # Install Jadx
    - name: Install Jadx
      run: |
          JADX_VERSION=$(curl -s "https://api.github.com/repos/skylot/jadx/releases/latest" | grep -Po '"tag_name": "v\K[0-9.]+')
          curl -Lo jadx.zip "https://github.com/skylot/jadx/releases/latest/download/jadx-${JADX_VERSION}.zip"
          unzip jadx.zip -d jadx-temp
          sudo mkdir -p /home/runner/work/Rabbit-R1/bin
          sudo mv jadx-temp/bin/jadx /home/runner/work/Rabbit-R1/jadx
          sudo mv jadx-temp/bin/jadx-gui /home/runner/work/Rabbit-R1/jadx-gui
          sudo mv jadx-temp/lib /home/runner/work/Rabbit-R1/lib
          sudo chmod +x /home/runner/work/Rabbit-R1/jadx
          sudo chmod +x /home/runner/work/Rabbit-R1/jadx-gui

      # Run the build.sh script with the selected build type
    - name: Run build script with selected build type
      run: |
          BUILD_TYPE="${{ github.event.inputs.build_type }}"
          echo "Running build with type: $BUILD_TYPE"
          bash ./build.sh "$BUILD_TYPE"

      # Upload APKs to GitHub release
    - name: Upload APK to Release
      uses: softprops/action-gh-release@v1
      with:
          files: |
            original/apk/*.apk
            android/apk/*.apk
            switch/apk/*.apk
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
