name: Build APK and Decompile with JADX

on:
  push:
    branches:
      - main  # Atau branch yang kamu inginkan
  workflow_dispatch:

jobs:
  build_and_decompile:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Install dependencies
    - name: Install required dependencies
      run: |
        sudo apt update
        sudo apt install -y openjdk-11-jdk wget unzip

    # Download and extract JADX
    - name: Download JADX
      run: |
        wget https://github.com/skylot/jadx/releases/download/v1.4.7/jadx-1.4.7.zip
        unzip jadx-1.4.7.zip -d jadx

    # Set up the folder structure for JADX
    - name: Set up JADX folder structure
      run: |
        sudo mkdir -p /usr/local/bin
        sudo mkdir -p /usr/local/lib
        
        # Memindahkan file binary yang ada ke folder bin
        sudo mv jadx/bin/jadx /usr/local/bin/
        sudo mv jadx/bin/jadx-gui /usr/local/bin/
        
        # Memindahkan semua file .jar ke dalam /usr/local/lib/
        sudo mv jadx/lib/* /usr/local/lib/

    # Display Java version
    - name: Display Java version
      run: java -version

    # Decompile APK with JADX
    - name: Decompile APK using JADX
      run: |
        # Assumes APK is available at a specific location, modify as needed
        /usr/local/bin/jadx -d decompiled_apk /path/to/your.apk

    # (Optional) Upload decompiled files to artifacts
    - name: Upload Decompiled APK Files
      uses: actions/upload-artifact@v4
      with:
        name: decompiled-apk
        path: decompiled_apk/

    # Cleanup
    - name: Clean up
      run: |
        rm -rf jadx-1.4.7.zip jadx-1.4.7
