name: APK Builder & Release

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y apktool zip wget unzip

          # Install JADX tanpa prompt overwrite
          wget https://github.com/skylot/jadx/releases/download/v1.4.7/jadx-1.4.7.zip
          unzip -o -q jadx-1.4.7.zip
          sudo mv jadx/bin/jadx /usr/local/bin/
          sudo chmod +x /usr/local/bin/jadx

      - name: Make build script executable
        run: chmod +x build.sh

      - name: Run build for all types
        run: |
          for i in 1 2 3; do
            echo $i | ./build.sh
          done

      - name: Zip all APKs
        run: |
          mkdir -p release
          find . -type f -name "*.apk" -exec zip -j release/Rabbit_R1_Builds.zip {} +

      - name: Create GitHub Release and upload ZIP
        uses: softprops/action-gh-release@v1
        with:
          name: "Rabbit APK Build - ${{ github.run_number }}"
          tag_name: "build-${{ github.run_number }}"
          files: release/Rabbit_R1_Builds.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
