name: APK Builder & Release

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y apktool zip wget unzip

          # Download dan ekstrak JADX tanpa interaksi
          wget https://github.com/skylot/jadx/releases/download/v1.4.7/jadx-1.4.7.zip
          unzip -q -o jadx-1.4.7.zip

          # Cek struktur folder setelah ekstraksi untuk memastikan lokasi bin/jadx
          ls -R jadx-1.4.7

          # Pindahkan file 'jadx', 'jadx-gui', 'jadx.run', dan 'jadx-gui.run' ke /usr/local/bin/ dan pastikan sudah executable
          sudo mv jadx-1.4.7/bin/jadx /usr/local/bin/
          sudo mv jadx-1.4.7/bin/jadx-gui /usr/local/bin/
          sudo mv jadx-1.4.7/bin/jadx.run /usr/local/bin/
          sudo mv jadx-1.4.7/bin/jadx-gui.run /usr/local/bin/

          # Ubah hak akses agar file-file tersebut bisa dieksekusi
          sudo chmod +x /usr/local/bin/jadx
          sudo chmod +x /usr/local/bin/jadx-gui
          sudo chmod +x /usr/local/bin/jadx.run
          sudo chmod +x /usr/local/bin/jadx-gui.run

          # Pindahkan seluruh file .jar dari lib/ ke /usr/local/lib/jadx/
          sudo mkdir -p /usr/local/lib/jadx
          sudo mv jadx-1.4.7/lib/* /usr/local/lib/jadx/

          # Setel CLASSPATH untuk seluruh .jar di /usr/local/lib/jadx/
          export CLASSPATH=/usr/local/lib/jadx/*

          # Menjalankan Jadx untuk memastikan semuanya berjalan
          jadx -v

      - name: Make build script executable
        run: chmod +x build.sh

      - name: Run build for all types
        run: |
          for i in 1 2 3; do
            echo $i | ./build.sh
          done

      - name: Zip all APKs
        run: |
          mkdir -p release
          find . -type f -name "*.apk" -exec zip -j release/Rabbit_R1_Builds.zip {} +

      - name: Create GitHub Release and upload ZIP
        uses: softprops/action-gh-release@v1
        with:
          name: "Rabbit APK Build - ${{ github.run_number }}"
          tag_name: "build-${{ github.run_number }}"
          files: release/Rabbit_R1_Builds.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
